#!/bin/bash
# Stable Diffusion 1.5 Generation Script for Academic_Quantum_Campus
# Auto-generated by VisualMILFDistrictGenerator

curl -X POST "http://localhost:7860/api/v1/txt2img" \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "gothic academic library, quantum physics equations floating as holograms, computational matrices, library bench converted to study station with restraint elements, quantum computer displays, purple ambient lighting, scholarly atmosphere with BDSM elements, ornate gothic architecture, mystical knowledge aesthetic, masterpiece, best quality, ultra-detailed, professional photography, dramatic lighting, artistic composition, mature themes, sophisticated adult content, artistic nudity, tasteful sensuality",
    "negative_prompt": "low quality, blurry, distorted, ugly, deformed, bad anatomy",
    "width": 1024,
    "height": 768,
    "steps": 30,
    "cfg_scale": 7.5,
    "sampler_name": "DPM++ 2M Karras",
    "seed": -1,
    "batch_size": 1,
    "n_iter": 1,
    "save_images": true,
    "send_images": true
  }' \
  -o "Academic_Quantum_Campus_generation_result.json"

echo "🎨 Stable Diffusion generation completed for Academic_Quantum_Campus"
echo "📁 Result saved to: Academic_Quantum_Campus_generation_result.json"
