#!/bin/bash
# Stable Diffusion 1.5 Generation Script for Aerospace_Command_Station
# Auto-generated by VisualMILFDistrictGenerator

curl -X POST "http://localhost:7860/api/v1/txt2img" \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "space-age renaissance command center, orbital navigation displays, star charts, command chair as captain throne with restraint capabilities, zero gravity chambers, blue atmospheric lighting, space renaissance aesthetic, celestial navigation equipment, sophisticated space opera ambiance, masterpiece, best quality, ultra-detailed, professional photography, dramatic lighting, artistic composition, mature themes, sophisticated adult content, artistic nudity, tasteful sensuality",
    "negative_prompt": "low quality, blurry, distorted, ugly, deformed, bad anatomy",
    "width": 1024,
    "height": 768,
    "steps": 30,
    "cfg_scale": 7.5,
    "sampler_name": "DPM++ 2M Karras",
    "seed": -1,
    "batch_size": 1,
    "n_iter": 1,
    "save_images": true,
    "send_images": true
  }' \
  -o "Aerospace_Command_Station_generation_result.json"

echo "🎨 Stable Diffusion generation completed for Aerospace_Command_Station"
echo "📁 Result saved to: Aerospace_Command_Station_generation_result.json"
