#!/bin/bash
# Stable Diffusion 1.5 Generation Script for Financial_Crypto_Exchange
# Auto-generated by VisualMILFDistrictGenerator

curl -X POST "http://localhost:7860/api/v1/txt2img" \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "art deco financial exchange, cryptocurrency displays, trading algorithms visualization, golden lighting, luxurious trading desk as command center, vault door converted to throne, wealth symbols, economic power aesthetic, golden ratio architecture, opulent BDSM elements, masterpiece, best quality, ultra-detailed, professional photography, dramatic lighting, artistic composition, mature themes, sophisticated adult content, artistic nudity, tasteful sensuality",
    "negative_prompt": "low quality, blurry, distorted, ugly, deformed, bad anatomy",
    "width": 1024,
    "height": 768,
    "steps": 30,
    "cfg_scale": 7.5,
    "sampler_name": "DPM++ 2M Karras",
    "seed": -1,
    "batch_size": 1,
    "n_iter": 1,
    "save_images": true,
    "send_images": true
  }' \
  -o "Financial_Crypto_Exchange_generation_result.json"

echo "🎨 Stable Diffusion generation completed for Financial_Crypto_Exchange"
echo "📁 Result saved to: Financial_Crypto_Exchange_generation_result.json"
