#!/bin/bash
# Stable Diffusion 1.5 Generation Script for Medical_Bio_Enhancement_Ward
# Auto-generated by VisualMILFDistrictGenerator

curl -X POST "http://localhost:7860/api/v1/txt2img" \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "futuristic medical facility, bio-enhancement pods, medical examination table as BDSM apparatus, biometric scanners, cyan lighting, cyberpunk medical aesthetic, enhancement chambers, clinical precision with sensual undertones, sterile surfaces with leather restraints, masterpiece, best quality, ultra-detailed, professional photography, dramatic lighting, artistic composition, mature themes, sophisticated adult content, artistic nudity, tasteful sensuality",
    "negative_prompt": "low quality, blurry, distorted, ugly, deformed, bad anatomy",
    "width": 1024,
    "height": 768,
    "steps": 30,
    "cfg_scale": 7.5,
    "sampler_name": "DPM++ 2M Karras",
    "seed": -1,
    "batch_size": 1,
    "n_iter": 1,
    "save_images": true,
    "send_images": true
  }' \
  -o "Medical_Bio_Enhancement_Ward_generation_result.json"

echo "🎨 Stable Diffusion generation completed for Medical_Bio_Enhancement_Ward"
echo "📁 Result saved to: Medical_Bio_Enhancement_Ward_generation_result.json"
