#!/bin/bash
# Stable Diffusion 1.5 Generation Script for Rustbeltet_Underground_Workshop
# Auto-generated by VisualMILFDistrictGenerator

curl -X POST "http://localhost:7860/api/v1/txt2img" \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "industrial steampunk workshop, rust and copper textures, steam pipes, welding sparks, workshop bench converted to BDSM restraint table, mechanical vises, leather and metal restraints, atmospheric steam, warm orange lighting, gritty realism, detailed metalwork, cinematic composition, masterpiece, best quality, ultra-detailed, professional photography, dramatic lighting, artistic composition, mature themes, sophisticated adult content, artistic nudity, tasteful sensuality",
    "negative_prompt": "low quality, blurry, distorted, ugly, deformed, bad anatomy",
    "width": 1024,
    "height": 768,
    "steps": 30,
    "cfg_scale": 7.5,
    "sampler_name": "DPM++ 2M Karras",
    "seed": -1,
    "batch_size": 1,
    "n_iter": 1,
    "save_images": true,
    "send_images": true
  }' \
  -o "Rustbeltet_Underground_Workshop_generation_result.json"

echo "🎨 Stable Diffusion generation completed for Rustbeltet_Underground_Workshop"
echo "📁 Result saved to: Rustbeltet_Underground_Workshop_generation_result.json"
