#!/bin/bash
# Stable Diffusion 1.5 Generation Script for Skyskraperen_Sektor_7_Alpha
# Auto-generated by VisualMILFDistrictGenerator

curl -X POST "http://localhost:7860/api/v1/txt2img" \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "cyberpunk corporate tower, neo-brutalist architecture, neon purple lighting, glass reflections, surveillance drones, executive office converted into BDSM chamber, leather executive chair as dominatrix throne, high-tech holographic displays, atmospheric fog, cinematic lighting, photorealistic, 8k resolution, masterpiece, best quality, ultra-detailed, professional photography, dramatic lighting, artistic composition, mature themes, sophisticated adult content, artistic nudity, tasteful sensuality",
    "negative_prompt": "low quality, blurry, distorted, ugly, deformed, bad anatomy",
    "width": 1024,
    "height": 768,
    "steps": 30,
    "cfg_scale": 7.5,
    "sampler_name": "DPM++ 2M Karras",
    "seed": -1,
    "batch_size": 1,
    "n_iter": 1,
    "save_images": true,
    "send_images": true
  }' \
  -o "Skyskraperen_Sektor_7_Alpha_generation_result.json"

echo "🎨 Stable Diffusion generation completed for Skyskraperen_Sektor_7_Alpha"
echo "📁 Result saved to: Skyskraperen_Sektor_7_Alpha_generation_result.json"
